import Head from "next/head";
import React from "react";
import FeedPublic from "../src/Components/FeedPublic/FeedPublic";
import Footer from "../src/Components/Footer";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DESENVOLVIMENTO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="title animeLeft">Pagina inicial</h1>
      <div>
        <FeedPublic />
      </div>
      {/* <Footer /> */}
    </div>
  );
}
